apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: demoservice-rc
  name: demoservice-rc
spec:
  replicas: 3
  selector:
    name: demoservice
  template:
    metadata:
      labels:
        name: demoservice
    spec:
      containers:
      - name: demoservice-container
        image: somakdocker/demoservice
        ports:
            - containerPort: 5000
              name: http-server

---

apiVersion: v1
kind: Service
metadata:
  name: service1
  labels:
    name: service1
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  selector:
    name: demoservice